
services:
  pokedexapp:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    image: pokedex-dockerfile
    container_name: pokedexapp
    restart: always
    ports:
      - "${PORT}:${PORT}"
    environment:
      MONGODB: ${MONGODB}
      PORT: "${PORT}"
      DEAFULT_LIMIT: ${DEFAULT_LIMIT}
  db:
    image: mongo:5
    container_name: mongo-poke
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_DATABASE: nest-pokemon
    volumes:
      - ./mongo:/data/db